"""Markdown formatter for pre-ADR transcript documents."""

from __future__ import annotations

import re
from datetime import datetime

from .channels import VideoMetadata
from .transcript import Chapter


class ADRMarkdownFormatter:
    """Format transcript data into structured pre-ADR markdown.

    Output is a structured document ready for LLM processing
    into a full Architecture Decision Record.
    """

    TEMPLATE = """# {prefix}-{number:03d}: {title}

## Status: Raw Transcript
## Date: {date}

## Source

- **Channel:** {channel}
- **Published:** {published_date}
- **Duration:** {duration}
- **Video URL:** {url}
- **Video ID:** `{video_id}`
- **Batch ID:** `{batch_id}`

---

## Topics Detected

{topics}

---

## Chapter Markers

{chapters}

---

## Transcript

{transcript}

---

*Generated by yt-adr-feed v0.1.0 on {generated_at}*
"""

    def __init__(self, file_prefix: str = "TRANSCRIPT"):
        self.file_prefix = file_prefix

    def format(
        self,
        video: VideoMetadata,
        transcript: str,
        topics: list[str],
        chapters: list[Chapter],
        number: int,
        batch_id: str,
    ) -> str:
        """Render a complete pre-ADR markdown document."""
        topics_str = self._format_topics(topics)
        chapters_str = self._format_chapters(chapters)
        duration_str = self._format_duration(video.duration_seconds)

        return self.TEMPLATE.format(
            prefix=self.file_prefix,
            number=number,
            title=video.title,
            date=datetime.now().strftime("%Y-%m-%d"),
            channel=video.channel,
            published_date=video.published_date.strftime("%Y-%m-%d"),
            duration=duration_str,
            url=video.url,
            video_id=video.id,
            batch_id=batch_id,
            topics=topics_str,
            chapters=chapters_str,
            transcript=transcript,
            generated_at=datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        )

    def generate_filename(self, video: VideoMetadata, number: int) -> str:
        """Generate a deterministic filename for the transcript.

        Format: TRANSCRIPT-001-ibm-technology.md
        """
        slug = self._slugify(video.channel)
        return f"{self.file_prefix}-{number:03d}-{slug}.md"

    @staticmethod
    def _format_topics(topics: list[str]) -> str:
        if not topics:
            return "*(No topics detected)*"
        return "\n".join(f"- {topic}" for topic in topics)

    @staticmethod
    def _format_chapters(chapters: list[Chapter]) -> str:
        if not chapters:
            return "*(No chapter markers found)*"
        return "\n".join(f"- **{ch.timestamp}** — {ch.title}" for ch in chapters)

    @staticmethod
    def _format_duration(seconds: int) -> str:
        if seconds <= 0:
            return "Unknown"
        hours = seconds // 3600
        minutes = (seconds % 3600) // 60
        secs = seconds % 60
        if hours > 0:
            return f"{hours}h {minutes}m {secs}s"
        return f"{minutes}m {secs}s"

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert text to URL-safe slug."""
        text = text.lower()
        text = re.sub(r"[^a-z0-9\s-]", "", text)
        text = re.sub(r"[\s]+", "-", text)
        text = re.sub(r"-+", "-", text)
        return text.strip("-")[:50]
