"""Git workflow: clone, branch, commit, push, and create GitHub PRs."""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import uuid
from pathlib import Path

import requests

from .exceptions import GitError

logger = logging.getLogger(__name__)


class GitWorkflow:
    """Manage git operations for pushing transcript markdown to GitHub.

    Workflow: clone → branch → add files → commit → push → create PR → cleanup.
    Requires GITHUB_TOKEN env var for PR creation.
    """

    def __init__(
        self,
        repo_url: str,
        branch_target: str = "main",
        author_name: str = "yt-adr-feed",
        author_email: str = "yt-adr-feed@noreply.github.com",
        branch_prefix: str = "transcripts/",
        transcript_dir: str = "transcripts",
    ):
        self.repo_url = repo_url
        self.branch_target = branch_target
        self.author_name = author_name
        self.author_email = author_email
        self.branch_prefix = branch_prefix
        self.transcript_dir = transcript_dir
        self.work_dir = Path(f"/tmp/yt-adr-{uuid.uuid4().hex[:8]}")

    def clone(self):
        """Clone the target repository to a temp directory."""
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self._run_git(["clone", "--depth", "1", self.repo_url, str(self.work_dir)])
        logger.info(f"Cloned {self.repo_url} to {self.work_dir}")

    def create_branch(self, batch_id: str) -> str:
        """Create a feature branch for this batch of transcripts."""
        branch_name = f"{self.branch_prefix}{batch_id}"
        self._run_git(
            ["checkout", "-b", branch_name],
            cwd=self.work_dir,
        )
        logger.info(f"Created branch: {branch_name}")
        return branch_name

    def add_files(self, files: dict[str, str]):
        """Write and stage transcript markdown files.

        Args:
            files: dict of {filename: content} to add to the transcript directory.
        """
        target_dir = self.work_dir / self.transcript_dir
        target_dir.mkdir(parents=True, exist_ok=True)

        for filename, content in files.items():
            filepath = target_dir / filename
            filepath.write_text(content)
            self._run_git(
                ["add", str(Path(self.transcript_dir) / filename)],
                cwd=self.work_dir,
            )
            logger.debug(f"Staged file: {filename}")

    def commit(self, batch_id: str, file_count: int) -> str:
        """Create a commit with conventional commit message.

        Returns the commit hash.
        """
        message = (
            f"docs(transcripts): add batch {batch_id}\n\n"
            f"Auto-generated by yt-adr-feed\n"
            f"Files: {file_count} transcript(s)"
        )

        self._run_git(
            [
                "-c", f"user.name={self.author_name}",
                "-c", f"user.email={self.author_email}",
                "commit", "-m", message,
            ],
            cwd=self.work_dir,
        )

        # Get commit hash
        result = self._run_git(["rev-parse", "HEAD"], cwd=self.work_dir)
        commit_hash = result.stdout.strip()
        logger.info(f"Committed: {commit_hash[:8]}")
        return commit_hash

    def push(self, branch_name: str):
        """Push the branch to origin."""
        self._run_git(
            ["push", "-u", "origin", branch_name],
            cwd=self.work_dir,
        )
        logger.info(f"Pushed branch: {branch_name}")

    def create_pr(self, branch_name: str, batch_id: str, files: dict[str, str]) -> str:
        """Create a GitHub Pull Request via REST API.

        Requires GITHUB_TOKEN environment variable.
        Returns the PR URL.
        """
        token = os.environ.get("GITHUB_TOKEN")
        if not token:
            raise GitError("GITHUB_TOKEN environment variable not set")

        owner, repo = self._parse_repo_url()

        # Build PR body with file listing
        file_list = "\n".join(f"- `{f}`" for f in files.keys())
        body = (
            f"## Transcript Batch: `{batch_id}`\n\n"
            f"Auto-generated by **yt-adr-feed**.\n\n"
            f"### Files\n{file_list}\n\n"
            f"---\n"
            f"*Review and merge to add these transcripts to the ADR corpus.*"
        )

        try:
            response = requests.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers={
                    "Authorization": f"token {token}",
                    "Accept": "application/vnd.github.v3+json",
                },
                json={
                    "title": f"docs(transcripts): batch {batch_id}",
                    "body": body,
                    "head": branch_name,
                    "base": self.branch_target,
                },
                timeout=30,
            )
            response.raise_for_status()
        except requests.RequestException as e:
            raise GitError(f"Failed to create PR: {e}") from e

        pr_url = response.json().get("html_url", "")
        logger.info(f"Created PR: {pr_url}")
        return pr_url

    def cleanup(self):
        """Remove the temporary work directory."""
        if self.work_dir.exists():
            shutil.rmtree(self.work_dir, ignore_errors=True)
            logger.debug(f"Cleaned up: {self.work_dir}")

    def _parse_repo_url(self) -> tuple[str, str]:
        """Extract owner/repo from git URL.

        Handles both SSH and HTTPS formats:
        - git@github.com:owner/repo.git
        - https://github.com/owner/repo.git
        """
        url = self.repo_url.replace(".git", "")

        if url.startswith("git@"):
            # SSH format: git@github.com:owner/repo
            parts = url.split(":")[-1].split("/")
        elif "github.com" in url:
            # HTTPS format: https://github.com/owner/repo
            parts = url.rstrip("/").split("/")[-2:]
        else:
            raise GitError(f"Cannot parse repo URL: {self.repo_url}")

        if len(parts) != 2:
            raise GitError(f"Cannot extract owner/repo from: {self.repo_url}")

        return parts[0], parts[1]

    @staticmethod
    def _run_git(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
        """Execute a git command and return the result."""
        cmd = ["git"] + args
        try:
            result = subprocess.run(
                cmd,
                cwd=cwd,
                capture_output=True,
                text=True,
                timeout=120,
                check=True,
            )
            return result
        except subprocess.CalledProcessError as e:
            raise GitError(f"Git command failed: {' '.join(cmd)}\n{e.stderr}") from e
        except subprocess.TimeoutExpired as e:
            raise GitError(f"Git command timed out: {' '.join(cmd)}") from e
