apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yt-adr-feed.fullname" . }}-config
  labels:
    {{- include "yt-adr-feed.labels" . | nindent 4 }}
data:
  channels.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
